### ISSUE TITLE
Page is layout incrementally

### ISSUE THREAD

**Issue by riedelcastro** [wolfe-pack/moro#18]
This can sometimes be fun to watch, but also creates some unwanted effects. For example, in the early stages of the layout process the code appears twice, and in the navigation bar. Also, the wolfe tutorial uses a dark background, but the default background is something white. This creates a flashing effect.

**Comment by sameersingh** [comment]
This should be mostly addressed now. All non-code cells are laid out in parallel, and code cells have to be incremental. Due to the recent refactoring, there should not be weird inconsistencies, and CSS can be used to get rid of flashing, if any.

Closing for now.
