### ISSUE TITLE
Scala annotations should be highlighted

### ISSUE THREAD

**Issue by riedelcastro** [wolfe-pack/moro#30]
They are important for annotating objectives...

**Comment by sameersingh** [comment]
Perhaps not relevant anymore? Anyway, wontfix, since probably not a simple ACE editor modification.

**Comment by riedelcastro** [comment]
Not that crucial anymore, but there is a quite heavily used macro annotation still (@domain). AFAIK it isn't too hard to add to the recognized keyword set of ACE. But definitely not a priority, and I can look into that if I feel there is the ned.

**Comment by sameersingh** [comment]
Sure. Feel free to reopen if you want.
