### ISSUE TITLE
Globally define latex macros

### ISSUE THREAD

**Issue by riedelcastro** [wolfe-pack/moro#44]
I often reuse the same latex code in several cells and notebooks, and it would be great to define macros for this globally.

**Comment by sameersingh** [comment]
Support for `prefixHTML` added to config files by 06cbfbc and 5c31b50.

For adding latex macros, add something like this to the `moro.compilers` section of the config file (first one creates a standalone macro, and the second a macro for single-argument function):
```
latex {
  imports = [
    "\\def\\RR{\\bf R}",
    "\\def\\bold#1{\\alpha: #1}"
  ]
}
```
Do you think this should be part of the notebook config?

**Comment by sameersingh** [comment]
Leaving notebook config for future.
