### ISSUE TITLE
Per Cell toolbar should be vertical

### ISSUE THREAD

**Issue by riedelcastro** [wolfe-pack/moro#58]
And appear below the "run" button. Currently the toolbar tends to interfere with the first lines of markdown I am writing.

**Comment by sameersingh** [comment]
That'll be a problem when the editor is not long enough. I think we need to
move it too, so let's think of other options.

**Comment by riedelcastro** [comment]
By long you mean vertical length? That wouldn't be a problem because that middle bar is completely empty anyway. It would interfere with the horizontal lines but I don't think that's too bad.

**Comment by sameersingh** [comment]
Yeah I mean vertical length. I guess you mean it's okay if it goes over to
the next editor, but the way the divs are nested, and my very limited
knowledge of css, I don't know how to have the button div overlap across
editors.

**Comment by sameersingh** [comment]
The toolbar now fades out if the mouse is not moved, so the first line of the editor will not be hidden (for long). Not a perfect solution, since you still can't select etc on the first line without bringing up the toolbar, but works for keyboard focused editing quite well.
