### ISSUE TITLE
First compilation of Scala cell gives error in LazyLogging

### ISSUE THREAD

**Issue by rockt** [wolfe-pack/moro#64]
I always get this error for the first Scala cell. All subsequent Scala cells are compiled fine though and when I recompile the first cell then it works.

```
error: missing or invalid dependency detected while loading class file 'LazyLogging.class'.
Could not access type Logging in package com.typesafe.scalalogging,
because it (or its dependencies) are missing. Check your build definition for
missing or conflicting dependencies. (Re-run with `-Ylog-classpath` to see the problematic classpath.)
A full rebuild may help if 'LazyLogging.class' was compiled against an incompatible version of com.typesafe.scalalogging.
```

**Comment by riedelcastro** [comment]
Add the logging classes to the conf `classesForJarPath`, like [here](https://github.com/wolfe-pack/moro/blob/master/conf/reference.conf#L112-112).

**Comment by rockt** [comment]
Thanks! I think the reference.conf is outdated since the logging class has to go into the scala compiler (there is no wolfe compiler anymore, no?).

**Comment by riedelcastro** [comment]
Yep, it's outdated.
