### ISSUE TITLE
Easier toggling of "hide cell output"

### ISSUE THREAD

**Issue by riedelcastro** [wolfe-pack/moro#65]
I find myself hiding the output of quite a few scala cells recently, and going to the cell settings menu is a little slow. Could there be a direct icon/button (for example, an "closed/open eye" icon under the play button to hide output?

**Comment by sameersingh** [comment]
Could do.

On Thu, Jun 18, 2015 at 12:41 PM, Sebastian Riedel <notifications@github.com

**Comment by sameersingh** [comment]
The icon doesn't change, it's always "open", but should work fine otherwise.
