### ISSUE TITLE
Make reveal.js transition type a cell configuration in notebook

### ISSUE THREAD

**Issue by rockt** [wolfe-pack/moro#68]
I need transition=none for some cells in my moro notebook in present mode :)
Would also be sufficient to have a general field in the cell configuration to add reveal.js section attributes (like transition type, background color/image etc.)

**Comment by sameersingh** [comment]
I can add this config option on the cells, and point you to how to access
them from javascript, but you'll have to implement the part where it's used
in the reveal template. Okay?

**Comment by sameersingh** [comment]
Added a config option, it should show up as a text field in the editor now. This should show you how to add per cell config options in the future.

To use it, see the javascript [here](https://github.com/wolfe-pack/moro/blob/master/public/javascripts/moro-static.js#L52) for how the `fragment` is included. Note that adding it there adds it to all the static views, which might be fine if the classes are unused, but if you're adding something more complicated, you might want to do it only in the reveal template [here](https://github.com/wolfe-pack/moro/blob/master/app/views/present.scala.html#L141).

Finally, if these `reveal_params` can be used for `fragment` as well, let's get ride of the `fragment` config option.

Let me know if you have any questions!

**Comment by sameersingh** [comment]
Closing since I haven't heard anything back. Reopen if still a problem.
