### ISSUE TITLE
Hide Editor for scala cells not working?

### ISSUE THREAD

**Issue by riedelcastro** [wolfe-pack/moro#70]
I would like to only show the output of a scala cell in the static/present view, not the editor. I disabled "show editor?" in the cell config view, but this doesn't seem to make a difference.

**Comment by sameersingh** [comment]
Ah, this feature was implemented only for non-code cells, i.e. if you want to show the editor for cells that otherwise you wouldn't show the editor for. I didn't think of the use case where the editor of code cells should be hidden, but output shown.

Clearly this is inconsistent. I will fix this.
