### ISSUE TITLE
Sometimes it requires choosing a mode several times for it to lock

### ISSUE THREAD

**Issue by riedelcastro** [wolfe-pack/moro#71]
For example, if the current mode is scala I need to choose markdown three times for it to actually change the mode (some of us have problems changing it at all).

**Comment by sameersingh** [comment]
Can you see if there are any errors on the console when this happens next,
and send them to me?

**Comment by riedelcastro** [comment]
No errors. I think it's a GUI thing.

**Comment by sameersingh** [comment]
I think I fixed this. Reopen if this is still a problem.
