### ISSUE TITLE
'Request Entity Too Large' when storing a notebook with a larger generated d3 graph

### ISSUE THREAD

**Issue by riedelcastro** [wolfe-pack/moro#82]
the generated HTML in this case is quite long, with the javascript data array having 3000 points. Maybe this is the reason. 

This happens when storing

http://localhost:9000/doc/editor/01_tasks/0x_languagemodels

in the stat nlp book. Console doesn't seem to show the error (or I can't find it).

**Comment by sameersingh** [comment]
This is hitting against the REST limit, I'll raise it even more.

**Comment by sameersingh** [comment]
can you check and close if this is solved?

**Comment by riedelcastro** [comment]
Seems to work!
